package com.edu.dlnu.mapper;

import com.edu.dlnu.been.Car;
import com.edu.dlnu.been.CarExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    long countByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    int deleteByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    @Delete({
        "delete from car",
        "where carID = #{carid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    @Insert({
        "insert into car (carID, carBrand, ",
        "carModel, carStruct, ",
        "carDisplacement, isManual, ",
        "maxMum, originalPrice, ",
        "discount)",
        "values (#{carid,jdbcType=VARCHAR}, #{carbrand,jdbcType=VARCHAR}, ",
        "#{carmodel,jdbcType=VARCHAR}, #{carstruct,jdbcType=VARCHAR}, ",
        "#{cardisplacement,jdbcType=DOUBLE}, #{ismanual,jdbcType=TINYINT}, ",
        "#{maxmum,jdbcType=INTEGER}, #{originalprice,jdbcType=DOUBLE}, ",
        "#{discount,jdbcType=DOUBLE})"
    })
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    List<Car> selectByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "carID, carBrand, carModel, carStruct, carDisplacement, isManual, maxMum, originalPrice, ",
        "discount",
        "from car",
        "where carID = #{carid,jdbcType=VARCHAR}"
    })
//    @ResultMap("BaseResultMap")
    Car selectByPrimaryKey(String carid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated
     */
    @Update({
        "update car",
        "set carBrand = #{carbrand,jdbcType=VARCHAR},",
          "carModel = #{carmodel,jdbcType=VARCHAR},",
          "carStruct = #{carstruct,jdbcType=VARCHAR},",
          "carDisplacement = #{cardisplacement,jdbcType=DOUBLE},",
          "isManual = #{ismanual,jdbcType=TINYINT},",
          "maxMum = #{maxmum,jdbcType=INTEGER},",
          "originalPrice = #{originalprice,jdbcType=DOUBLE},",
          "discount = #{discount,jdbcType=DOUBLE}",
        "where carID = #{carid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Car record);

    List<Car> findAllCars();
}