package com.edu.dlnu.mapper;

import com.edu.dlnu.been.Order;
import com.edu.dlnu.been.OrderExample;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from order",
        "where orderNum = #{ordernum,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String ordernum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into order (orderNum, userName, ",
        "carID, pickupTime, ",
        "returnTime, orderStatus, ",
        "orderCost)",
        "values (#{ordernum,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{carid,jdbcType=VARCHAR}, #{pickuptime,jdbcType=DATE}, ",
        "#{returntime,jdbcType=DATE}, #{orderstatus,jdbcType=INTEGER}, ",
        "#{ordercost,jdbcType=DOUBLE})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "orderNum, userName, carID, pickupTime, returnTime, orderStatus, orderCost",
        "from order",
        "where orderNum = #{ordernum,jdbcType=VARCHAR}"
    })
//    @ResultMap("BaseResultMap")
    Order selectByPrimaryKey(String ordernum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Update({
        "update order",
        "set userName = #{username,jdbcType=VARCHAR},",
          "carID = #{carid,jdbcType=VARCHAR},",
          "pickupTime = #{pickuptime,jdbcType=DATE},",
          "returnTime = #{returntime,jdbcType=DATE},",
          "orderStatus = #{orderstatus,jdbcType=INTEGER},",
          "orderCost = #{ordercost,jdbcType=DOUBLE}",
        "where orderNum = #{ordernum,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);

    List<Order> findAllOrders();
}