package com.edu.dlnu.been;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carID
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carBrand
     *
     * @mbg.generated
     */
    private String carbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carModel
     *
     * @mbg.generated
     */
    private String carmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carStruct
     *
     * @mbg.generated
     */
    private String carstruct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carDisplacement
     *
     * @mbg.generated
     */
    private Double cardisplacement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.isManual
     *
     * @mbg.generated
     */
    private Byte ismanual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.maxMum
     *
     * @mbg.generated
     */
    private Integer maxmum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.originalPrice
     *
     * @mbg.generated
     */
    private Double originalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.discount
     *
     * @mbg.generated
     */
    private Double discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carID
     *
     * @return the value of car.carID
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carID
     *
     * @param carid the value for car.carID
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carBrand
     *
     * @return the value of car.carBrand
     *
     * @mbg.generated
     */
    public String getCarbrand() {
        return carbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carBrand
     *
     * @param carbrand the value for car.carBrand
     *
     * @mbg.generated
     */
    public void setCarbrand(String carbrand) {
        this.carbrand = carbrand == null ? null : carbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carModel
     *
     * @return the value of car.carModel
     *
     * @mbg.generated
     */
    public String getCarmodel() {
        return carmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carModel
     *
     * @param carmodel the value for car.carModel
     *
     * @mbg.generated
     */
    public void setCarmodel(String carmodel) {
        this.carmodel = carmodel == null ? null : carmodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carStruct
     *
     * @return the value of car.carStruct
     *
     * @mbg.generated
     */
    public String getCarstruct() {
        return carstruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carStruct
     *
     * @param carstruct the value for car.carStruct
     *
     * @mbg.generated
     */
    public void setCarstruct(String carstruct) {
        this.carstruct = carstruct == null ? null : carstruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carDisplacement
     *
     * @return the value of car.carDisplacement
     *
     * @mbg.generated
     */
    public Double getCardisplacement() {
        return cardisplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carDisplacement
     *
     * @param cardisplacement the value for car.carDisplacement
     *
     * @mbg.generated
     */
    public void setCardisplacement(Double cardisplacement) {
        this.cardisplacement = cardisplacement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.isManual
     *
     * @return the value of car.isManual
     *
     * @mbg.generated
     */
    public Byte getIsmanual() {
        return ismanual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.isManual
     *
     * @param ismanual the value for car.isManual
     *
     * @mbg.generated
     */
    public void setIsmanual(Byte ismanual) {
        this.ismanual = ismanual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.maxMum
     *
     * @return the value of car.maxMum
     *
     * @mbg.generated
     */
    public Integer getMaxmum() {
        return maxmum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.maxMum
     *
     * @param maxmum the value for car.maxMum
     *
     * @mbg.generated
     */
    public void setMaxmum(Integer maxmum) {
        this.maxmum = maxmum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.originalPrice
     *
     * @return the value of car.originalPrice
     *
     * @mbg.generated
     */
    public Double getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.originalPrice
     *
     * @param originalprice the value for car.originalPrice
     *
     * @mbg.generated
     */
    public void setOriginalprice(Double originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.discount
     *
     * @return the value of car.discount
     *
     * @mbg.generated
     */
    public Double getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.discount
     *
     * @param discount the value for car.discount
     *
     * @mbg.generated
     */
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
}